// Turns the Figma-exported SVGs in design/icons/ into React components (components/icons/figma.tsx).
// Geometry and root width/height are kept exactly; only the baked colour becomes currentColor,
// so the nav icon colour can tween and one icon works on any surface.
// Run: node scripts/gen-icons.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const dir = join(root, 'design/icons');
const pascal = (s) => s.replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase());

const out = [
  '// AUTO-GENERATED by scripts/gen-icons.mjs from design/icons/*.svg (exported from Figma). Do not edit.',
  "import type { SVGProps } from 'react';",
  '',
  'type IconProps = SVGProps<SVGSVGElement>;',
  '',
];
for (const file of readdirSync(dir).filter((f) => f.endsWith('.svg')).sort()) {
  let svg = readFileSync(join(dir, file), 'utf8').trim();
  svg = svg
    .replace(/ (preserveAspectRatio|overflow|style|id)="[^"]*"/g, '')
    .replace(/(stroke|fill)="(?!none)[^"]*"/g, '$1="currentColor"')
    .replace(/stroke-width=/g, 'strokeWidth=')
    .replace(/stroke-linecap=/g, 'strokeLinecap=')
    .replace(/stroke-linejoin=/g, 'strokeLinejoin=')
    .replace(/fill-rule=/g, 'fillRule=')
    .replace(/clip-rule=/g, 'clipRule=')
    .replace(/stroke-dasharray=/g, 'strokeDasharray=')
    .replace(/ xmlns="[^"]*"/, '')
    .replace(/<g>\s*/g, '')
    .replace(/\s*<\/g>/g, '')
    .replace(/<svg ([^>]*)>/, '<svg $1 aria-hidden="true" focusable="false" {...props}>')
    .replace(/\n\s*/g, ' ');
  out.push(`export function ${pascal(file.replace('.svg', ''))}Icon(props: IconProps) {`, `  return (${svg});`, '}', '');
}
writeFileSync(join(root, 'components/icons/figma.tsx'), out.join('\n'));
console.log('icons: wrote components/icons/figma.tsx');
