// Generates styles/tokens.css from design/Default.tokens.json (the Figma
// "dashboard variables" export) plus design/extras.tokens.json (Figma styles
// that aren't variables). The output is a Tailwind v4 @theme block, so every
// token becomes both a CSS variable and a utility (bg-surface-default, p-16,
// rounded-12, text-13 ...). Tailwind's own default palette/radii/type scale
// are cleared first, so only tokens exist as utilities.
//
// Run: npm run tokens   (also runs automatically before dev and build)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const figma = JSON.parse(readFileSync(join(root, 'design/Default.tokens.json'), 'utf8'));
const extras = JSON.parse(readFileSync(join(root, 'design/extras.tokens.json'), 'utf8'));

const lines = [];
const walk = (node, path = []) => {
  if (node && typeof node === 'object' && '$value' in node) return emit(path, node);
  for (const [k, v] of Object.entries(node ?? {})) if (!k.startsWith('$')) walk(v, [...path, k]);
};

const px = (n) => `${+Number(n).toFixed(4)}px`;
const color = (v) => {
  if (v.alpha !== undefined && v.alpha < 1) {
    const [r, g, b] = v.components.map((c) => Math.round(c * 255));
    return `rgba(${r}, ${g}, ${b}, ${+v.alpha.toFixed(3)})`;
  }
  return v.hex.toUpperCase();
};

// Figma variables changed since the JSON export (extras.override): their new values win.
const overrides = Object.fromEntries(Object.entries(extras.override ?? {}).filter(([k]) => !k.startsWith('$')));

function emit(path, token) {
  const [group, ...rest] = path;
  const v = token.$value;
  const name = rest.join('-');
  const override = overrides[path.join('/')];
  switch (group) {
    case 'color':
      return lines.push(`  --color-${name}: ${override ? override.value.toUpperCase() : color(v)};`);
    case 'spacing':
      return lines.push(`  --spacing-${name}: ${px(v)};`);
    case 'radius':
      return lines.push(`  --radius-${name}: ${px(v)};`);
    case 'stroke':
      return lines.push(`  --stroke-${name.replace(/^weight-/, '')}: ${px(v)};`);
    case 'opacity':
      return lines.push(`  --opacity-${name}: ${v / 100};`);
    case 'typography': {
      const [kind, key] = rest;
      if (kind === 'font-family')
        return lines.push(
          `  --font-${key}: ${key === 'geist' ? 'var(--font-geist-sans), ' : ''}"${v}", ui-sans-serif, system-ui, sans-serif;`,
        );
      if (kind === 'font-size') return lines.push(`  --text-${key}: ${px(v)};`);
      if (kind === 'font-weight') return lines.push(`  --font-weight-${key}: ${v};`);
      if (kind === 'line-height') return lines.push(`  --leading-${key.replace(/^pixels-/, '')}: ${px(v)};`);
      if (kind === 'letter-spacing') return lines.push(`  --tracking-${key}: ${px(v)};`);
      return; // paragraph spacing / indent: always 0, not used
    }
  }
}

walk(figma);

const extraLines = [];
for (const [k, t] of Object.entries(extras.shadow)) extraLines.push(`  --shadow-${k}: ${t.value};`);
for (const [k, t] of Object.entries(extras.gradient)) {
  extraLines.push(`  --gradient-${k}: linear-gradient(to bottom, ${t.from}, ${t.to});`);
  extraLines.push(`  --gradient-${k}-from: ${t.from};`, `  --gradient-${k}-to: ${t.to};`);
}
for (const [k, t] of Object.entries(extras.color ?? {})) extraLines.push(`  --color-${k}: ${t.value};`);
for (const [k, t] of Object.entries(extras.text ?? {})) extraLines.push(`  --text-${k}: ${px(t.value)};`);
for (const [k, t] of Object.entries(extras.layout)) extraLines.push(`  --spacing-${k}: ${px(t.value)};`);

const css = `/* AUTO-GENERATED by scripts/gen-tokens.mjs — do not edit by hand.
 * Source: design/Default.tokens.json (Figma "dashboard variables") + design/extras.tokens.json.
 * Fractional names (spacing/16-6, radius/8-3, font-size/14-11 …) come from the scaled
 * History screenshots — don't use them on real components (brief A8). */
@theme static {
  --color-*: initial;
  --radius-*: initial;
  --text-*: initial;
  --font-*: initial;
  --leading-*: initial;
  --tracking-*: initial;
  --shadow-*: initial;

  /* Figma variables */
${lines.join('\n')}

  /* Figma styles and layout constants (design/extras.tokens.json) */
${extraLines.join('\n')}
}
`;

mkdirSync(join(root, 'styles'), { recursive: true });
writeFileSync(join(root, 'styles/tokens.css'), css);
console.log(`tokens: wrote styles/tokens.css (${lines.length} variables, ${extraLines.length} extras)`);
